#+ summary: Delete A and B
#+ method: POST
#+ tags:
#+   - my first tag

PREFIX ex: <http://example.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE DATA {
    GRAPH ex:myGraph {
        
        ex:ali a foaf:Person ;
               foaf:name "Alice" .
        
        ex:bob a foaf:Person ;
               foaf:name "Bob" .
    }
}
