#+ summary: Insert A, B, C and D in ex:myGraph
#+ method: POST
#+ tags:
#+   - my tag

PREFIX ex: <http://example.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT DATA {
    GRAPH ex:myGraph {
        
        ex:ali a foaf:Person ;
               foaf:name "Alice" .
        
        ex:bob a foaf:Person ;
               foaf:name "Bob" .
        
        ex:car a foaf:Person ;
               foaf:name "Carl" .
        
        ex:dyl a foaf:Person ;
               foaf:name "Dylan" .
    }
}
